# Generated by Django 6.0.3 on 2026-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_postathomepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postathomepage',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
