# Generated by Django 6.0.3 on 2026-03-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_postathomepage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentofPost',
            fields=[
                ('postathomepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Post.postathomepage')),
                ('comment', models.TextField(max_length=1000)),
            ],
            bases=('Post.postathomepage',),
        ),
        migrations.AlterField(
            model_name='postathomepage',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
