# Generated by Django 6.0.3 on 2026-03-13 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_postathomepage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='postcatageory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catageory', models.CharField(choices=[('Sports', 'Sports'), ('Entertaintment', 'Entertaintment'), ('News', 'News'), ('Meme', 'Meme')])),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Post.postathomepage')),
            ],
        ),
    ]
