# Generated by Django 6.0.3 on 2026-03-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_postcatageory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postcatageory',
        ),
    ]
